### PR TITLE
register any function that is exported from a gulpfile

### PR DESCRIPTION
**Pull request by phated**
@thejameskyle As per gulpjs/gulp/issues/1305 - can you try this out?

@contra you good with this functionality being added?

### CODE REVIEW

**Comment by thejameskyle** [comment]
Tried getting this working, and wasn't able to https://github.com/thejameskyle/__gulp-exports

Not sure if I'm missing something. I'm depending on this branch: https://github.com/thejameskyle/__gulp-exports/blob/master/package.json#L16

**Comment by phated** [comment]
@thejameskyle I didn't add it for gulp 3.9 but maybe I could/should

**Comment by thejameskyle** [comment]
It doesn't work for 4.0 either: https://github.com/thejameskyle/__gulp-exports/tree/4.0

**Comment by phated** [comment]
@thejameskyle yeah, digging into it...npm doesn't seem to know how to dedupe github dependencies, so you end up with the gulp-cli#4.0 branch as a dependency of gulp, which is used instead of the gulp-cli you install as a dep

**Comment by phated** [comment]
@thejameskyle deleting `node_modules/gulp/node_modules/gulp-cli` allows it to work

**Comment by thejameskyle** [comment]
Ah yup, manually running `npm dedupe` works too. Thanks! This is awesome

**Comment by contra** [comment]
Yeah this makes perfect sense

**Comment by phated** [comment]
Was easy enough to backport too!  3.7 and up will support this if someone is using this CLI separately

**Pull request merged**
