### PR TITLE
Docs: Clarify CLI semantics when listing more than one task

### PR DESCRIPTION
**Pull request by kylecordes**
Make the same CLI doc change here as in the gulpjs repo:

https://github.com/gulpjs/gulp/pull/1916

### CODE REVIEW

**Comment by phated** [comment]
Awesome, thanks!

**Comment by phated** [comment]
@kylecordes would you mind making a similar change to the README of this project - probably in the https://github.com/gulpjs/gulp-cli#tasks section

**Comment by kylecordes** [comment]
@phated sure, I will peek at it tomorrow.

**Comment by kylecordes** [comment]
@phated https://github.com/gulpjs/gulp-cli/pull/106

**Pull request merged**
