### PR TITLE
Switching to jscs-preset-gulp preset

### PR DESCRIPTION
**Pull request by pdehaan**
```sh
$ npm run lint

> gulp-cli@0.3.0 lint /Users/pdehaan/dev/github/gulp-cli
> jshint lib index.js --reporter node_modules/jshint-stylish --exclude node_modules && jscs index.js lib bin test


✔ No problems

$ echo $?
0
```

### CODE REVIEW

**Comment by Romanx** [comment]
Not to bump a dead commit but shouldn't this also be in the 4.0 branch?

**Comment by phated** [comment]
I'll be rebasing it later

**Comment by Romanx** [comment]
@phated still hasn't seem to have happened? Just wondering for my pr :)

**Comment by phated** [comment]
@Romanx oh, I meant after your PR was merged.  Was waiting on a way to test different gulp versions.

**Comment by Romanx** [comment]
no problem, my mistake!

**Pull request merged**
