### PR TITLE
Update: Add flag/config for running tasks from CLI in series

### PR DESCRIPTION
**Pull request by erikkemperman**
https://github.com/gulpjs/gulp-cli/issues/93

Sorry for all the PRs, going away for a couple of days and wanted to get this out.

I figured this ought to be a flag too, after all, since I imagine it might not usually make sense to do this per-module, but rather for occasional single runs of the CLI.

### CODE REVIEW

**Comment by phated** [comment]
@erikkemperman I'm more inclined to take this as a "config only" option.  I'm hesitant to add more CLI options (people already complain we collide with their custom options).

**Comment by erikkemperman** [comment]
@phated

Well, okay, easy enough to take the flag stuff out of the PR of course. But I hope you don't mind one little attempt at persuasion, because I for one would probably want to use this for occasional runs and perhaps not always as a structural element of my build...

I get the complaints about colliding with people's custom flags, but might argue the one exception would be if gulp-cli now implemented the same functionality out of the box that I had to do myself before.

And with "series" it seems likely that if folks built that themselves, it would probably be doing something very much like what that flag would do in this PR?

But anyway, having said that, if you're adamant about it I'll happily amend the PR, probably some time this week.

**Comment by phated** [comment]
@sttk do you have any thoughts about this? Specifically whether it should be config-only or config + flag

**Comment by sttk** [comment]
@phated I think both cli flag and config are good, and this flag will be useful.
Adding a new flag is worried about conflicts with user-defined flags, but there would be few cases about this flag.

**Comment by phated** [comment]
Cherry-picked this into master as c454a6d2196c02b7b8cb891b73b357d43fb03e8e and did some conflict resolution/cleanup.

@erikkemperman Thanks for your patience with me on this - I'm going to land it as a "new" feature in 2.0 incase it is breaking for anyone relying on `--series` within their gulpfile.

**Comment by erikkemperman** [comment]
@phated That’s great, thanks a lot!

**Pull request closed without merging**
