### PR TITLE
Added preferGlobal

### PR DESCRIPTION
**Pull request by callumacrae**
Seems like it fits on this repo. https://docs.npmjs.com/files/package.json#preferglobal

### CODE REVIEW

**Comment by phated** [comment]
I think this will cause the error to show up when it is a dependency of gulp.

**Comment by callumacrae** [comment]
Fair enough. Is there any way to test that without pushing it up to npm?

**Comment by phated** [comment]
you can use npm to install from github with `npm install repo_name/project_name`

**Comment by phated** [comment]
I don't think it is worth it to add preferGlobal here.  The npm warnings are annoying.

**Pull request closed without merging**
